- name: Configure frontend server
  become: yes
  hosts: frontend
  tasks:
    - name: install nginx server
      ansible.builtin.dnf: 
        name: nginx
        state: latest

    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: delete default website
      ansible.builtin.path:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.path:
        path: /usr/share/nginx/html
        state: directory

    - name: download and extract frontend code
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip
        remote_src: yes

    - name: copy backend conf
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: restart nginx server
      ansible.builtin.service:
        name: nginx
        state: restart
